# Auto-generated by Neural Glass AI Orchestrator
# Enterprise Security & Quality Inspected


import subprocess

def execute_command(command):
    try:
        # Using subprocess.run with shell=True can pose a security risk if you're planning to execute user-supplied input,
        # because it can lead to shell injection attacks.
        result = subprocess.run(command, shell=True, check=True, capture_output=True, text=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        return f"Command failed with return code {e.returncode}"
   