# Auto-generated by Neural Glass AI Orchestrator
# Enterprise Security & Quality Inspected


from jwt_handler import encode_token, decode_token
from exec_runner import execute_command
from config import AWS_ACCESS_KEY

if __name__ == '__main__':
    # Testing jwt_handler functions
    payload = { 'exp': int(time.time()) + 100, 'iat': int(time.time()), 'sub': 'test_user' }
    token = encode_token(payload)
    print(decode_token(token))

    # Testing exec_runner function
    command = 'echo Hello, World!'
    print(execute_command(command))
   