# Auto-generated by Neural Glass AI Orchestrator
# Enterprise Security & Quality Inspected

import sqlite3

def create_expense_db(db_file):
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except sqlite3.Error as e:
        print(e)
        return None

def close_connection(conn):
    if conn:
        conn.close()