"""
Sample Plugin: Enterprise Header Injector
Appends standard licensing and metadata comments to top-level Python files.
"""

from typing import Dict
from core.plugins import BasePlugin


class LicenseHeaderPlugin(BasePlugin):
    name = "EnterpriseHeaderPlugin"
    version = "1.1.0"
    description = "Injects enterprise license header comments into generated Python source files."

    async def on_post_generation(self, files: Dict[str, str], state: dict) -> Dict[str, str]:
        header = "# Auto-generated by Neural Glass AI Orchestrator\n# Enterprise Security & Quality Inspected\n\n"
        updated_files = {}

        for filename, code in files.items():
            if filename.endswith(".py") and not code.startswith("# Auto-generated"):
                updated_files[filename] = header + code
            else:
                updated_files[filename] = code

        return updated_files